import { bootstrapApplication } from '@angular/platform-browser';
import { addIcons } from 'ionicons';
import {
  add,
  addCircle,
  arrowBack,
  arrowBackCircle,
  backspaceOutline,
  banOutline,
  camera,
  checkmark,
  checkmarkCircle,
  checkmarkOutline,
  chevronBack,
  chevronBackOutline,
  copyOutline,
  documentTextOutline,
  flag,
  flameOutline,
  flashOutline,
  handRight,
  handRightOutline,
  chevronForward,
  chevronForwardOutline,
  close,
  documentText,
  downloadOutline,
  enter,
  eyeOutline,
  happyOutline,
  lockClosedOutline,
  logoGoogle,
  mailOutline,
  people,
  peopleOutline,
  person,
  personAdd,
  personAddOutline,
  personCircleOutline,
  personOutline,
  personRemoveOutline,
  ribbonOutline,
  shareSocialOutline,
  star,
  starOutline,
  statsChart,
  statsChartOutline,
  timeOutline,
  trash,
  trophy,
  trophyOutline,
} from 'ionicons/icons';
import { appConfig } from './app/app.config';
import { AppComponent } from './app/app.component';

addIcons({
  add,
  'add-circle': addCircle,
  'arrow-back': arrowBack,
  'arrow-back-circle': arrowBackCircle,
  'backspace-outline': backspaceOutline,
  'ban-outline': banOutline,
  camera,
  checkmark,
  'checkmark-circle': checkmarkCircle,
  'checkmark-outline': checkmarkOutline,
  'chevron-back-outline': chevronBackOutline,
  'chevron-forward-outline': chevronForwardOutline,
  'copy-outline': copyOutline,
  'document-text-outline': documentTextOutline,
  flag,
  'flame-outline': flameOutline,
  'flash-outline': flashOutline,
  'hand-right': handRight,
  'hand-right-outline': handRightOutline,
  'chevron-back': chevronBack,
  'chevron-forward': chevronForward,
  close,
  'document-text': documentText,
  'download-outline': downloadOutline,
  enter,
  'eye-outline': eyeOutline,
  'happy-outline': happyOutline,
  'lock-closed-outline': lockClosedOutline,
  'logo-google': logoGoogle,
  'mail-outline': mailOutline,
  people,
  'people-outline': peopleOutline,
  person,
  'person-add': personAdd,
  'person-add-outline': personAddOutline,
  'person-circle-outline': personCircleOutline,
  'person-outline': personOutline,
  'person-remove-outline': personRemoveOutline,
  'ribbon-outline': ribbonOutline,
  'share-social-outline': shareSocialOutline,
  star,
  'star-outline': starOutline,
  'stats-chart': statsChart,
  'stats-chart-outline': statsChartOutline,
  'time-outline': timeOutline,
  trash,
  trophy,
  'trophy-outline': trophyOutline,
});

bootstrapApplication(AppComponent, appConfig).catch((err) => console.error(err));
