import { bootstrapApplication } from '@angular/platform-browser';
import { addIcons } from 'ionicons';
import {
  add,
  addCircle,
  arrowBack,
  arrowBackCircle,
  backspaceOutline,
  banOutline,
  camera,
  checkmark,
  checkmarkCircle,
  checkmarkOutline,
  chevronBack,
  copyOutline,
  flag,
  handRight,
  chevronForward,
  close,
  documentText,
  downloadOutline,
  enter,
  eyeOutline,
  happyOutline,
  logoGoogle,
  people,
  person,
  personAdd,
  personAddOutline,
  personCircleOutline,
  personRemoveOutline,
  shareSocialOutline,
  statsChart,
  timeOutline,
  trash,
  trophy,
} from 'ionicons/icons';
import { appConfig } from './app/app.config';
import { AppComponent } from './app/app.component';

addIcons({
  add,
  'add-circle': addCircle,
  'arrow-back': arrowBack,
  'arrow-back-circle': arrowBackCircle,
  'backspace-outline': backspaceOutline,
  'ban-outline': banOutline,
  camera,
  checkmark,
  'checkmark-circle': checkmarkCircle,
  'checkmark-outline': checkmarkOutline,
  'copy-outline': copyOutline,
  flag,
  'hand-right': handRight,
  'chevron-back': chevronBack,
  'chevron-forward': chevronForward,
  close,
  'document-text': documentText,
  'download-outline': downloadOutline,
  enter,
  'eye-outline': eyeOutline,
  'happy-outline': happyOutline,
  'logo-google': logoGoogle,
  people,
  person,
  'person-add': personAdd,
  'person-add-outline': personAddOutline,
  'person-circle-outline': personCircleOutline,
  'person-remove-outline': personRemoveOutline,
  'share-social-outline': shareSocialOutline,
  'stats-chart': statsChart,
  'time-outline': timeOutline,
  trash,
  trophy,
});

bootstrapApplication(AppComponent, appConfig).catch((err) => console.error(err));
